### ISSUE TITLE
黑屋跟打器二改并收费？

### ISSUE THREAD

**Issue by Matthew-Harris-36** [taliove/tygdq#2]
我怀疑黑屋跟打器用了您的代码，换了套界面，并将其中的功能收费。因为本人并非程序员，所以想请您看看。
黑屋跟打器下载地址：https://wwc.lanzouq.com/iDxyg08o0uwf

**Comment by taliove** [comment]
感谢反馈，我现在才看到。我去看看。

**Comment by taliove** [comment]
我看了一下，使用的技术栈不同。整体而言在界面、功能和概念上有相似的地方，但不足以说明是换壳。作者应该是花费了大量的心思在里面。
